import React from "react";
import { Document, Page, View, Text } from "@react-pdf/renderer";
import {
  sharedStyles, DocHeader, FieldRow, TextBlock, SignatureBlock, DocFooter,
} from "@/components/agm-pdf-shared";
import { P6_PDF_COPY } from "@/lib/agm-p6-copy";

/**
 * Package 6, section 5.3 - the nominee holder's platform instruction. This
 * is what the member sends to their own platform, so it carries only
 * content relevant to the platform - no mention of CSL's own confirmation
 * step, which belongs in the email around it, not the document itself.
 *
 * Same content as the on-screen text version on app/proxy/AppointmentForm.tsx
 * - the instruction wording must not drift between the two.
 */

export type NomineeInstructionPdfData = {
  fullName: string;
  email: string;
  nomineePlatform: string;
  shareClass: string | null;
  sharesHeld: string | null;
  appointeeName: string;
  signatureName: string;
  signedAt: string;
  meetingRef: string;
};

export function NomineeInstructionPdf(d: NomineeInstructionPdfData) {
  const instructionText =
    `Please appoint ${d.appointeeName} as my proxy to vote on my behalf at the Celtic plc Annual General Meeting, on all resolutions, in accordance with my instructions.`;

  return (
    <Document title={`CSL Platform Instruction - ${d.fullName}`} author="Celtic Supporters Limited">
      <Page size="A4" style={sharedStyles.page}>
        <DocHeader org="Celtic Supporters Limited" title={`Proxy Voting Instruction - ${d.meetingRef}`} />

        <View style={sharedStyles.body}>
          <Text style={sharedStyles.footerNote}>{P6_PDF_COPY.nomineeInstructionFooter}</Text>

          <Text style={sharedStyles.sectionHead}>To</Text>
          <FieldRow label="Platform" value={d.nomineePlatform} />

          <Text style={sharedStyles.sectionHead}>From</Text>
          <FieldRow label="Name" value={d.fullName} />
          <FieldRow label="Email" value={d.email} />
          <FieldRow label="Share class" value={d.shareClass ?? "Not stated"} />
          <FieldRow label="Shares held" value={d.sharesHeld ?? "Not stated"} />

          <Text style={sharedStyles.sectionHead}>Instruction</Text>
          <TextBlock label="Voting instruction" text={instructionText} />

          <SignatureBlock signatureName={d.signatureName} signedAt={d.signedAt} />
        </View>

        <DocFooter generatedNote={`Generated by Celtic Supporters Limited on ${new Date().toLocaleDateString("en-GB")} for ${d.fullName} to send to ${d.nomineePlatform}.`} />
      </Page>
    </Document>
  );
}
