import React from "react";
import { Document, Page, View, Text } from "@react-pdf/renderer";
import {
  sharedStyles, DocHeader, FieldRow, TextBlock, SignatureBlock, DocFooter,
} from "@/components/agm-pdf-shared";
import { P6_PDF_COPY, COMPUTERSHARE_ADDRESS } from "@/lib/agm-p6-copy";

/**
 * Package 6, section 4.2 - the proxy appointment, direct holders only.
 * Nominee holders receive NomineeInstructionPdf instead, never this
 * document - a nominee's proxy is exercised by their platform, not lodged
 * with Computershare directly.
 *
 * This is NOT a reproduction of Celtic's own form of proxy. That form is
 * only enclosed with the physical mailing of the Notice of AGM, not
 * published in the Notice PDF itself, so there was nothing to mirror the
 * layout of. What follows instead satisfies the content requirements
 * Celtic's Notice of AGM 2025 states in notes 2 and 3: the appointee named,
 * the number of shares stated as an exact figure (note 2 - stating none, or
 * more than are held, may invalidate the appointment), the share class, and
 * the declaration as the signatory actually saw it.
 */

export type ProxyAppointmentPdfData = {
  fullName: string;
  addressLine1: string | null;
  addressLine2: string | null;
  addressTown: string | null;
  addressPostcode: string | null;
  email: string;
  computershareSrn: string | null;
  sharesHeldExact: number | null;
  shareClass: string | null;
  appointeeName: string;
  declarationSnapshot: string;
  signatureName: string;
  signedAt: string;
  lodgementPath: string;
  meetingRef: string;
};

function fullAddress(d: ProxyAppointmentPdfData): string {
  return [d.addressLine1, d.addressLine2, d.addressTown, d.addressPostcode].filter(Boolean).join(", ") || "Not stated";
}

export function ProxyAppointmentPdf(d: ProxyAppointmentPdfData) {
  return (
    <Document title={`CSL Proxy Appointment - ${d.fullName}`} author="Celtic Supporters Limited">
      <Page size="A4" style={sharedStyles.page}>
        <DocHeader org="Celtic Supporters Limited" title={`Proxy Appointment - ${d.meetingRef}`} />

        <View style={sharedStyles.body}>
          <Text style={sharedStyles.footerNote}>{P6_PDF_COPY.appointmentFooter}</Text>

          <Text style={sharedStyles.sectionHead}>Member appointing the proxy</Text>
          <FieldRow label="Name of member" value={d.fullName} />
          <FieldRow label="Address" value={fullAddress(d)} />
          <FieldRow label="Email" value={d.email} />
          <FieldRow label="Computershare account (SRN)" value={d.computershareSrn ?? "Not stated"} />
          <FieldRow label="Share class" value={d.shareClass ?? "Not stated"} />
          <FieldRow
            label="Number of shares"
            value={d.sharesHeldExact != null ? String(d.sharesHeldExact) : "Not stated"}
          />

          <Text style={sharedStyles.sectionHead}>Proxy appointed</Text>
          <FieldRow label="Proxy" value={d.appointeeName} />
          <TextBlock label="Declaration" text={d.declarationSnapshot} />

          <Text style={sharedStyles.sectionHead}>Lodgement</Text>
          <Text style={sharedStyles.textBlock}>
            {d.lodgementPath === "we-lodge"
              ? "TBD: Celtic Supporters Limited will lodge this appointment with Computershare on your behalf, ahead of the deadline."
              : `TBD: You chose to lodge this appointment yourself, by post to ${COMPUTERSHARE_ADDRESS}, or through Computershare's online Investor Centre. It must arrive no later than 24 hours before the meeting.`}
          </Text>

          <SignatureBlock signatureName={d.signatureName} signedAt={d.signedAt} />
        </View>

        <DocFooter generatedNote={`Generated by Celtic Supporters Limited on ${new Date().toLocaleDateString("en-GB")} from the online submission record. This is not a reproduction of Celtic plc's own form of proxy.`} />
      </Page>
    </Document>
  );
}
