import React from "react";
import { Document, Page, View, Text } from "@react-pdf/renderer";
import {
  sharedStyles, DocHeader, FieldRow, TextBlock, SignatureBlock, DocFooter,
} from "@/components/agm-pdf-shared";
import { P6_PDF_COPY } from "@/lib/agm-p6-copy";

/**
 * Package 6, section 4.1 - the requisition, one per signature. Field order
 * follows Appendix 1 of docs/agm/reference/ShareAction_UK_Guide_Shareholder_
 * Resolutions_2019.md (name of member, address, the sections 314/338
 * declaration frame, confirmations, signature, date) - member details
 * first, then the four texts, then the confirmations Appendix 1 itself
 * asks for, then signature and date.
 *
 * Two of Appendix 1's five confirmations are not reproduced: the amount
 * paid up on the shares, and an explicit "I do not hold these shares on
 * behalf of someone else" statement distinct from eligibility. Neither is
 * captured by CSL's own form (see docs/AGM_Build_Status.md's deferred
 * items) - this document cannot show what was never collected.
 *
 * All four texts come from the signature's own snapshot columns, never the
 * live wording - the entire reason those columns exist is so this document
 * shows what that person actually saw, unaffected by any later edit.
 */

export type RequisitionPdfData = {
  fullName: string;
  addressLine1: string | null;
  addressLine2: string | null;
  addressTown: string | null;
  addressPostcode: string | null;
  email: string;
  howHeld: string;
  computershareSrn: string | null;
  nomineePlatform: string | null;
  nomineePlatformOther: string | null;
  sharesHeld: string | null;
  shareClass: string | null;
  eligibilityConfirmed: boolean | null;
  resolutionSupported: boolean | null;
  resolutionSnapshot: string | null;
  supportingStatementSnapshot: string | null;
  declarationSnapshot: string | null;
  consentSnapshot: string | null;
  signatureName: string;
  signedAt: string;
  meetingRef: string;
};

function fullAddress(d: RequisitionPdfData): string {
  return [d.addressLine1, d.addressLine2, d.addressTown, d.addressPostcode].filter(Boolean).join(", ") || "Not stated";
}

export function RequisitionPdf(d: RequisitionPdfData) {
  return (
    <Document title={`CSL Requisition - ${d.fullName}`} author="Celtic Supporters Limited">
      <Page size="A4" style={sharedStyles.page}>
        <DocHeader org="Celtic Supporters Limited" title={`Shareholder Requisition - ${d.meetingRef}`} />

        <View style={sharedStyles.body}>
          <Text style={sharedStyles.footerNote}>{P6_PDF_COPY.requisitionFooter}</Text>

          <Text style={sharedStyles.sectionHead}>Member details</Text>
          <FieldRow label="Name of member" value={d.fullName} />
          <FieldRow label="Address" value={fullAddress(d)} />
          <FieldRow label="Email" value={d.email} />
          <FieldRow
            label="How shares are held"
            value={d.howHeld === "direct" ? "Directly registered (Computershare)" : "Through a nominee, broker or platform"}
          />
          {d.howHeld === "direct" && (
            <FieldRow label="Computershare account (SRN)" value={d.computershareSrn ?? "Not stated"} />
          )}
          {d.howHeld === "nominee" && (
            <FieldRow
              label="Nominee platform"
              value={(d.nomineePlatform === "Other" ? d.nomineePlatformOther : d.nomineePlatform) ?? "Not stated"}
            />
          )}
          <FieldRow label="Share class" value={d.shareClass ?? "Not stated"} />
          <FieldRow label="Shares held" value={d.sharesHeld ?? "Not stated"} />

          <Text style={sharedStyles.sectionHead}>Resolution</Text>
          <TextBlock label="Resolution" text={d.resolutionSnapshot ?? "Not available"} />
          {d.supportingStatementSnapshot && (
            <TextBlock label="Supporting statement" text={d.supportingStatementSnapshot} />
          )}

          <Text style={sharedStyles.sectionHead}>Declaration and consent</Text>
          <TextBlock label="Declaration" text={d.declarationSnapshot ?? "Not available"} />
          <TextBlock label="Consent" text={d.consentSnapshot ?? "Not available"} />

          <Text style={sharedStyles.sectionHead}>Confirmations</Text>
          <FieldRow
            label="Membership"
            value={d.eligibilityConfirmed ? "Confirmed - a member of Celtic plc" : "Not confirmed"}
          />
          <FieldRow
            label="Support for resolution"
            value={d.resolutionSupported ? "Confirmed - supports this resolution being put to the AGM" : "Not confirmed"}
          />

          <SignatureBlock signatureName={d.signatureName} signedAt={d.signedAt} />
        </View>

        <DocFooter generatedNote={`Generated by Celtic Supporters Limited on ${new Date().toLocaleDateString("en-GB")} from the online submission record.`} />
      </Page>
    </Document>
  );
}
